remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

title: "Md Mahmudul Haque"
subtitle: "AI Engineer • Computer Vision • NLP • LLMs/VLMs"
description: "AI Engineer • Computer Vision • NLP • LLMs/VLMs"

url: "https://alcatraz47.github.io"
baseurl: ""
repository: "alcatraz47/alcatraz47.github.io"

author: "mahmudul"
author_profile: true

minimal_mistakes_skin: "air"
read_time: true
breadcrumbs: true

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true

  - scope:
      path: "_pages"
      type: pages
    values:
      author_profile: true
